function baseline = p04_baseline(priorFaultProbability, ...
    alarmGivenFaultProbability, alarmGivenHealthyProbability, ...
    referencePopulationCount)
%P04_BASELINE Present exactly one deterministic Bayes update.

if nargin < 1
    priorFaultProbability = 0.01;
end
if nargin < 2
    alarmGivenFaultProbability = 0.90;
end
if nargin < 3
    alarmGivenHealthyProbability = 0.10;
end
if nargin < 4
    referencePopulationCount = 10000;
end

baseline = model(priorFaultProbability, alarmGivenFaultProbability, ...
    alarmGivenHealthyProbability, referencePopulationCount);

baselineFigureName = 'P04 baseline: alarm sources update belief';
existingBaseline = findall(groot, 'Type', 'figure', ...
    'Name', baselineFigureName);
if ~isempty(existingBaseline)
    close(existingBaseline);
end
figure('Name', baselineFigureName);

subplot(1,2,1);
beliefPercent = 100 * [baseline.prior_fault_probability, ...
    baseline.posterior_fault_given_alarm_probability];
bar(beliefPercent);
set(gca, 'XTick', 1:2, ...
    'XTickLabel', {'Prior fault', 'Fault after alarm'});
grid on;
xlabel('Belief stage');
ylabel('Fault probability (%)');
title('One alarm updates the fault belief');
ylim([0 max(10, 1.15 * max(beliefPercent))]);

subplot(1,2,2);
alarmSourceCounts = [baseline.expected_fault_alarm_count, ...
    baseline.expected_healthy_alarm_count];
bar(alarmSourceCounts);
set(gca, 'XTick', 1:2, ...
    'XTickLabel', {'Fault alarms', 'Healthy alarms'});
grid on;
xlabel('Source of observed alarms');
ylabel(sprintf('Expected alarms per %d systems (count)', ...
    baseline.reference_population_count));
title('The observed alarm column has two sources');
ylim([0 max(1, 1.15 * max(alarmSourceCounts))]);

fprintf(['Baseline: prior fault = %.2f%%, sensitivity = %.1f%%, ' ...
    'false-alarm probability = %.1f%%, P(alarm) = %.2f%%, ' ...
    'LR+ = %.2f, posterior fault = %.2f%%.\n'], ...
    100 * baseline.prior_fault_probability, ...
    100 * baseline.alarm_given_fault_probability, ...
    100 * baseline.alarm_given_healthy_probability, ...
    100 * baseline.alarm_probability, ...
    baseline.positive_likelihood_ratio, ...
    100 * baseline.posterior_fault_given_alarm_probability);
fprintf(['Expected alarm sources per %d systems: %.0f fault alarms + ' ...
    '%.0f healthy alarms = %.0f total alarms.\n'], ...
    baseline.reference_population_count, ...
    baseline.expected_fault_alarm_count, ...
    baseline.expected_healthy_alarm_count, ...
    baseline.expected_alarm_count);
end
