function run_checks
%RUN_CHECKS Independent numerical, limiting, and failure checks for P04.

checkCallerRngState = rng;
restoreCheckCallerRng = onCleanup(@() rng(checkCallerRngState)); %#ok<NASGU>

baselineA = model(0.01, 0.90, 0.10, 10000);
baselineB = model(0.01, 0.90, 0.10, 10000);
assert(isequal(baselineA, baselineB), ...
    'Repeated calls with identical inputs must be deterministic.');

independentJointFaultAlarm = 0.01 * 0.90;
independentJointFaultNoAlarm = 0.01 * (1 - 0.90);
independentJointHealthyAlarm = (1 - 0.01) * 0.10;
independentJointHealthyNoAlarm = (1 - 0.01) * (1 - 0.10);
independentAlarmProbability = ...
    independentJointFaultAlarm + independentJointHealthyAlarm;
independentPosteriorFault = ...
    independentJointFaultAlarm / independentAlarmProbability;
independentPosteriorHealthy = ...
    independentJointHealthyAlarm / independentAlarmProbability;

assert(abs(baselineA.joint_fault_alarm_probability - ...
    independentJointFaultAlarm) < 1e-12, ...
    'Fault-alarm joint mass must equal prior times sensitivity.');
assert(abs(baselineA.joint_healthy_alarm_probability - ...
    independentJointHealthyAlarm) < 1e-12, ...
    'Healthy-alarm joint mass must equal healthy prior times false-alarm probability.');
jointTotal = baselineA.joint_fault_alarm_probability + ...
    baselineA.joint_fault_no_alarm_probability + ...
    baselineA.joint_healthy_alarm_probability + ...
    baselineA.joint_healthy_no_alarm_probability;
assert(abs(jointTotal - 1) < 1e-12, ...
    'The four joint condition/alarm cells must conserve total probability.');
assert(abs(baselineA.joint_fault_alarm_probability + ...
    baselineA.joint_fault_no_alarm_probability - ...
    baselineA.prior_fault_probability) < 1e-12, ...
    'The fault row must sum back to the fault prior.');
assert(abs(baselineA.joint_healthy_alarm_probability + ...
    baselineA.joint_healthy_no_alarm_probability - ...
    baselineA.prior_healthy_probability) < 1e-12, ...
    'The healthy row must sum back to the healthy prior.');
assert(abs(baselineA.alarm_probability - ...
    independentAlarmProbability) < 1e-12, ...
    'Alarm probability must obey the law of total probability.');
assert(abs(baselineA.no_alarm_probability - ...
    (independentJointFaultNoAlarm + independentJointHealthyNoAlarm)) < 1e-12, ...
    'No-alarm probability must equal the other joint-table column.');
assert(abs(baselineA.posterior_fault_given_alarm_probability - ...
    independentPosteriorFault) < 1e-12 && ...
    abs(baselineA.posterior_healthy_given_alarm_probability - ...
    independentPosteriorHealthy) < 1e-12, ...
    'Reported posterior masses must match independent column normalization.');
assert(abs(baselineA.posterior_fault_given_alarm_probability + ...
    baselineA.posterior_healthy_given_alarm_probability - 1) < 1e-12, ...
    'The two posterior alarm sources must sum to one.');
assert(abs(baselineA.posterior_fault_given_alarm_probability - 1/12) < 1e-12, ...
    'Baseline posterior must equal 90/(90+990) = 1/12.');
assert(abs(baselineA.expected_fault_alarm_count - 90) < 1e-10 && ...
    abs(baselineA.expected_healthy_alarm_count - 990) < 1e-10 && ...
    abs(baselineA.expected_alarm_count - 1080) < 1e-10, ...
    'Baseline expected alarm counts must remain 90, 990, and 1080.');
assert(abs(baselineA.prior_fault_odds * ...
    baselineA.positive_likelihood_ratio - ...
    baselineA.posterior_fault_odds) < 1e-12, ...
    'Prior odds times LR+ must equal posterior odds.');

uninformative = model(0.37, 0.25, 0.25, 10000);
assert(abs(uninformative.posterior_fault_given_alarm_probability - 0.37) < 1e-12, ...
    'Equal likelihoods must leave the prior unchanged.');
zeroPrior = model(0.0, 0.90, 0.10, 10000);
onePrior = model(1.0, 0.90, 0.10, 10000);
assert(zeroPrior.posterior_fault_given_alarm_probability == 0 && ...
    onePrior.posterior_fault_given_alarm_probability == 1, ...
    'Possible alarms must preserve prior endpoints zero and one.');
perfectSpecificity = model(0.01, 0.90, 0.0, 10000);
assert(perfectSpecificity.posterior_fault_given_alarm_probability == 1 && ...
    isinf(perfectSpecificity.positive_likelihood_ratio), ...
    'Zero false-alarm probability must make a possible alarm decisive for fault.');
zeroSensitivity = model(0.01, 0.0, 0.10, 10000);
assert(zeroSensitivity.posterior_fault_given_alarm_probability == 0 && ...
    zeroSensitivity.positive_likelihood_ratio == 0, ...
    'Zero sensitivity must make a possible alarm decisive for healthy.');

priorLow = model(0.001, 0.90, 0.10, 10000);
priorMiddle = model(0.010, 0.90, 0.10, 10000);
priorHigh = model(0.100, 0.90, 0.10, 10000);
assert(priorLow.posterior_fault_given_alarm_probability < ...
    priorMiddle.posterior_fault_given_alarm_probability && ...
    priorMiddle.posterior_fault_given_alarm_probability < ...
    priorHigh.posterior_fault_given_alarm_probability, ...
    'The prior-only sweep must increase posterior fault probability.');
assert(priorLow.alarm_given_fault_probability == ...
    priorHigh.alarm_given_fault_probability && ...
    priorLow.alarm_given_healthy_probability == ...
    priorHigh.alarm_given_healthy_probability, ...
    'The prior sweep must preserve both likelihoods.');

falseAlarmLow = model(0.01, 0.90, 0.01, 10000);
falseAlarmMiddle = model(0.01, 0.90, 0.10, 10000);
falseAlarmHigh = model(0.01, 0.90, 0.30, 10000);
assert(falseAlarmLow.posterior_fault_given_alarm_probability > ...
    falseAlarmMiddle.posterior_fault_given_alarm_probability && ...
    falseAlarmMiddle.posterior_fault_given_alarm_probability > ...
    falseAlarmHigh.posterior_fault_given_alarm_probability, ...
    'The false-alarm-only sweep must decrease posterior fault probability.');
assert(abs(falseAlarmLow.expected_fault_alarm_count - ...
    falseAlarmHigh.expected_fault_alarm_count) < 1e-12 && ...
    falseAlarmLow.prior_fault_probability == ...
    falseAlarmHigh.prior_fault_probability, ...
    'The false-alarm sweep must preserve the fault-alarm path and prior.');

equalPrior = model(0.50, 0.90, 0.10, 10000);
brokenEqualPriorPosterior = 0.90 / (0.90 + 0.10);
assert(abs(equalPrior.posterior_fault_given_alarm_probability - ...
    brokenEqualPriorPosterior) < 1e-12, ...
    'The shortcut is valid only for its hidden equal-prior case.');
assert(abs(baselineA.posterior_fault_given_alarm_probability - ...
    brokenEqualPriorPosterior) > 0.80, ...
    'Using the equal-prior shortcut at a 1 percent prior must fail visibly.');

doublePopulation = model(0.01, 0.90, 0.10, 20000);
assert(abs(doublePopulation.expected_fault_alarm_count - ...
    2 * baselineA.expected_fault_alarm_count) < 1e-10 && ...
    abs(doublePopulation.expected_healthy_alarm_count - ...
    2 * baselineA.expected_healthy_alarm_count) < 1e-10, ...
    'Expected counts must scale linearly with reference population.');
assert(doublePopulation.posterior_fault_given_alarm_probability == ...
    baselineA.posterior_fault_given_alarm_probability, ...
    'Reference population scale must not change any posterior probability.');

rng(904, 'twister');
expectedNextUniformValue = rand;
expectedNextNormalValue = randn;
rng(904, 'twister');
model(0.01, 0.90, 0.10, 10000);
observedNextUniformValue = rand;
observedNextNormalValue = randn;
assert(observedNextUniformValue == expectedNextUniformValue && ...
    observedNextNormalValue == expectedNextNormalValue, ...
    'model must leave the caller RNG state unchanged.');

assertAnyError(@() model([0.01 0.02], 0.90, 0.10, 10000));
assertAnyError(@() model(0.01, 0.90 + 1i, 0.10, 10000));
assertAnyError(@() model(NaN, 0.90, 0.10, 10000));
assertAnyError(@() model(0.01, Inf, 0.10, 10000));
assertAnyError(@() model(0.01, 0.90, 0.10, 0));
assertAnyError(@() model(0.01, 0.90, 0.10, 10.5));
assertError(@() model(-0.01, 0.90, 0.10, 10000), ...
    'P04:InvalidProbability');
assertError(@() model(0.01, 1.01, 0.10, 10000), ...
    'P04:InvalidProbability');
assertError(@() model(0.01, 0.90, -0.01, 10000), ...
    'P04:InvalidProbability');
assertError(@() model(0.40, 0.0, 0.0, 10000), ...
    'P04:ImpossibleObservation');
assertError(@() model(1.0, 0.0, 0.5, 10000), ...
    'P04:ImpossibleObservation');
assertError(@() model(0.01, 0.90, 0.10, 10000001), ...
    'P04:ResourceBound');
minimumAccepted = model(0.01, 0.90, 0.10, 1);
maximumAccepted = model(0.01, 0.90, 0.10, 10000000);
assert(minimumAccepted.reference_population_count == 1 && ...
    maximumAccepted.reference_population_count == 10000000, ...
    'Both documented reference-population resource boundaries must be accepted.');

disp('P04 checks passed.');
end

function assertAnyError(operation)
didThrow = false;
try
    operation();
catch
    didThrow = true;
end
assert(didThrow, 'Expected malformed input to be rejected.');
end

function assertError(operation, expectedIdentifier)
caughtIdentifier = '';
try
    operation();
catch caught
    caughtIdentifier = caught.identifier;
end
assert(strcmp(caughtIdentifier, expectedIdentifier), ...
    'Expected error %s but caught %s.', expectedIdentifier, caughtIdentifier);
end
