function run_checks
%RUN_CHECKS Independent numerical, limiting, and failure checks for P02.

checkCallerRngState = rng;
restoreCheckCallerRng = onCleanup(@() rng(checkCallerRngState)); %#ok<NASGU>

baselineA = model(1000, 0.5, 1.0, 202);
baselineB = model(1000, 0.5, 1.0, 202);
assert(isequal(baselineA.samples_millivolts, baselineB.samples_millivolts), ...
    'Seeded samples must be deterministic.');
assert(isequal(baselineA.counts, baselineB.counts), ...
    'Seeded histogram counts must be deterministic.');
assert(sum(baselineA.counts) + baselineA.underflow_count + ...
    baselineA.overflow_count == baselineA.sample_count, ...
    'Counts and explicit tails must conserve every sample.');
assert(abs(sum(baselineA.probability_mass) - ...
    baselineA.included_fraction) < 1e-12, ...
    'Probability masses must use the total sample count.');
assert(abs(sum(baselineA.density_per_millivolt .* ...
    baselineA.bin_widths_millivolts) - baselineA.included_fraction) < 1e-12, ...
    'Density area must equal the included sample fraction.');
assert(abs(sum(baselineA.theoretical_probability_mass) + ...
    baselineA.theoretical_underflow_probability_mass + ...
    baselineA.theoretical_overflow_probability_mass - 1) < 1e-12, ...
    'Theoretical bin and tail masses must sum to one.');
assert(all(baselineA.counts >= 0 & baselineA.counts == floor(baselineA.counts)), ...
    'Histogram counts must be nonnegative integers.');
assert(all(diff(baselineA.bin_edges_millivolts) > 0), ...
    'Histogram edges must be strictly increasing.');

theoryFixture = model(2, 1, 1, 0, [-0.5 0.5], [-1 0 1]);
expectedTheoryMass = 0.5 * erf(1 / sqrt(2));
expectedTheoryDensity = exp(-0.5 * 0.5^2) / sqrt(2 * pi);
expectedNominalMassStandardError = sqrt(expectedTheoryMass * ...
    (1 - expectedTheoryMass) / 2);
assert(max(abs(theoryFixture.theoretical_probability_mass - ...
    expectedTheoryMass)) < 1e-12, ...
    'Gaussian bin masses must match the independent symmetric limit.');
assert(max(abs(theoryFixture.theoretical_density_per_millivolt - ...
    expectedTheoryDensity)) < 1e-12, ...
    'Gaussian center densities must match the independent analytic value.');
assert(max(abs(theoryFixture.nominal_probability_mass_standard_error - ...
    expectedNominalMassStandardError)) < 1e-12, ...
    'Nominal bin-mass uncertainty must follow the Bernoulli standard-error limit.');

expectedFarTailMass = 1.1285122074236006e-19;
positiveFarTail = model(1, 1, 1, 0, 9.5, [9 10]);
negativeFarTail = model(1, 1, 1, 0, -9.5, [-10 -9]);
assert(positiveFarTail.theoretical_probability_mass > 0 && ...
    negativeFarTail.theoretical_probability_mass > 0, ...
    'Valid far-tail bin masses must not cancel to zero.');
assert(abs(positiveFarTail.theoretical_probability_mass / ...
    expectedFarTailMass - 1) < 1e-10, ...
    'The positive 9-sigma to 10-sigma bin mass must match its stable reference.');
assert(abs(negativeFarTail.theoretical_probability_mass / ...
    expectedFarTailMass - 1) < 1e-10, ...
    'The negative 10-sigma to 9-sigma bin mass must match its stable reference.');
assert(positiveFarTail.nominal_probability_mass_standard_error > 0 && ...
    negativeFarTail.nominal_probability_mass_standard_error > 0, ...
    'A nonzero far-tail mass must retain nonzero nominal uncertainty.');

knownSamples = [-2 -1 -0.9 -0.1 0 0.4 1 2];
known = model(numel(knownSamples), 1, 1, 0, knownSamples, [-2 -1 0 1 2]);
assert(isequal(known.counts, [1 3 2 2]), ...
    'Known samples must follow the documented edge convention.');
assert(known.underflow_count == 0 && known.overflow_count == 0, ...
    'The exact-edge fixture should have no tail samples.');

boundarySamples = [-3 -2 -1 0 1 2 3];
boundary = model(numel(boundarySamples), 2, 1, 0, ...
    boundarySamples, [-2 0 2]);
assert(isequal(boundary.counts, [2 3]), ...
    'The final right edge must be included exactly once.');
assert(boundary.underflow_count == 1 && boundary.overflow_count == 1, ...
    'Samples outside the display range must remain explicit.');

asymmetricTailSamples = [-3 0 1 4 5];
asymmetricTails = model(numel(asymmetricTailSamples), 4, 1, 0, ...
    asymmetricTailSamples, [-2 2]);
expectedGaussianTailMass = 0.5 * erfc(2 / sqrt(2));
expectedGaussianInteriorMass = 1 - 2 * expectedGaussianTailMass;
expectedFullL1Error = abs(0.2 - expectedGaussianTailMass) + ...
    abs(0.4 - expectedGaussianInteriorMass) + ...
    abs(0.4 - expectedGaussianTailMass);
assert(abs(asymmetricTails.l1_probability_error - expectedFullL1Error) < 1e-12, ...
    'L1 probability error must include both explicit tail categories.');

oneBinSamples = [-1 -0.5 0 0.5 1];
oneBin = model(numel(oneBinSamples), 20, 1, 0, oneBinSamples, [-10 10]);
assert(isequal(oneBin.counts, 5), 'A one-bin limiting case must contain all samples.');
assert(abs(oneBin.probability_mass - 1) < 1e-12, ...
    'A containing one-bin histogram must have unit probability mass.');
assert(abs(oneBin.density_per_millivolt - 0.05) < 1e-12, ...
    'One-bin density must equal probability mass divided by width.');

uniformSamples = -1.875:0.25:1.875;
unequal = model(numel(uniformSamples), 1, 1, 0, ...
    uniformSamples, [-2 -1 1 2]);
assert(isequal(unequal.counts, [4 8 4]), ...
    'The wide middle bin should expose the raw-count distortion.');
assert(max(abs(unequal.density_per_millivolt - 0.25)) < 1e-12, ...
    'Width-normalized density must recover equal concentration in the broken fixture.');
naiveRawHeightArea = sum(unequal.probability_mass .* unequal.bin_widths_millivolts);
assert(abs(naiveRawHeightArea - 1) > 0.1, ...
    'Treating unequal-bin probability masses as heights must produce a recognizable wrong area.');
assert(abs(unequal.normalization_area - 1) < 1e-12, ...
    'Correct unequal-bin density must integrate to one when all samples are included.');

smallN = model(50, 0.5, 1.0, 311);
largeN = model(500, 0.5, 1.0, 311);
assert(isequal(smallN.samples_millivolts, largeN.samples_millivolts(1:50)), ...
    'The sample-count sweep must preserve the seeded sample prefix.');
assert(max(abs(largeN.nominal_probability_mass_standard_error * sqrt(10) - ...
    smallN.nominal_probability_mass_standard_error)) < 1e-12, ...
    'Nominal bin-mass uncertainty must shrink in proportion to 1/sqrt(N).');
fineBins = model(500, 0.25, 1.0, 311);
coarseBins = model(500, 1.0, 1.0, 311);
assert(numel(fineBins.counts) > numel(coarseBins.counts), ...
    'Smaller bin width must create more intervals at fixed range.');
assert(isequal(fineBins.samples_millivolts, coarseBins.samples_millivolts), ...
    'The bin-width sweep must preserve the seeded samples.');
controlledBinWidths = [0.25 0.5 1.0 2.0];
for widthIndex = 1:numel(controlledBinWidths)
    controlledWidth = model(50, controlledBinWidths(widthIndex), 1.0, 311);
    assert(controlledWidth.bin_edges_millivolts(1) == -4 && ...
        controlledWidth.bin_edges_millivolts(end) == 4, ...
        'Every interactive bin-width choice must preserve -4 to 4 mV support.');
end
underflowScale = model(1, 1e6, 1e-9, 0, 0);
assert(numel(underflowScale.counts) == 2 && sum(underflowScale.counts) == 1, ...
    'A tiny scale-to-width ratio must still produce bins and conserve its sample.');

rng(901, 'twister');
expectedNextUniformValue = rand;
expectedNextNormalValue = randn;
rng(901, 'twister');
model(100, 0.5, 1.0, 202);
observedNextUniformValue = rand;
observedNextNormalValue = randn;
assert(observedNextUniformValue == expectedNextUniformValue && ...
    observedNextNormalValue == expectedNextNormalValue, ...
    'model must restore the caller RNG state for uniform and normal draws.');

assertAnyError(@() model(0, 0.5, 1.0, 202));
assertAnyError(@() model(10.5, 0.5, 1.0, 202));
assertAnyError(@() model(10, 0, 1.0, 202));
assertAnyError(@() model(10, 0.5, 0, 202));
assertAnyError(@() model(10, 0.5, 1.0, -1));
assertError(@() model(50001, 0.5, 1.0, 202), 'P02:ResourceBound');
assertError(@() model(10, 0.5, 1.0, 4294967296), 'P02:InvalidSeed');
assertError(@() model(3, 0.5, 1.0, 0, [0 1]), 'P02:SampleCountMismatch');
assertError(@() model(3, 0.5, 1.0, 0, [NaN 1]), 'P02:SampleCountMismatch');
assertAnyError(@() model(3, 0.5, 1.0, 0, [0 NaN 1]));
assertError(@() model(3, 0.5, 1.0, 0, [0 0.5 1], [0 1 1]), ...
    'P02:InvalidEdges');
assertError(@() model(1, 0.5, 1.0, 0, 0, [0 realmin]), ...
    'P02:InvalidEdges');
assertError(@() model(1, 0.5, 1.0, 0, 0, [-realmax realmax]), ...
    'P02:ResourceBound');
assertError(@() model(1, 0.5, 1.0, 0, realmax, [-1 1]), ...
    'P02:ResourceBound');
twoHundredBins = model(3, 0.5, 1.0, 0, [0 0.5 1], linspace(-5, 5, 201));
assert(numel(twoHundredBins.counts) == 200, ...
    'The documented 200-bin resource boundary must remain accepted.');
tooManyEdges = linspace(-5, 5, 202);
assertError(@() model(3, 0.5, 1.0, 0, [0 0.5 1], tooManyEdges), ...
    'P02:ResourceBound');
assertError(@() model(3, realmin, 1.0, 0, [0 0.5 1]), ...
    'P02:ResourceBound');

disp('P02 checks passed.');
end

function assertAnyError(operation)
didThrow = false;
try
    operation();
catch
    didThrow = true;
end
assert(didThrow, 'Expected malformed input to be rejected.');
end

function assertError(operation, expectedIdentifier)
caughtIdentifier = '';
try
    operation();
catch caught
    caughtIdentifier = caught.identifier;
end
assert(strcmp(caughtIdentifier, expectedIdentifier), ...
    'Expected error %s but caught %s.', expectedIdentifier, caughtIdentifier);
end
