function interactive
%INTERACTIVE Explore sample count, noise scale, and calibration bias.

clear model;
modelFcn = @model;
existingUi = findall(groot, 'Type', 'figure', 'Name', ...
    'P05 Sample Mean Explorer');
if ~isempty(existingUi)
    close(existingUi);
end

fig = uifigure('Name', 'P05 Sample Mean Explorer', ...
    'Position', [100 100 1240 740]);
layout = uigridlayout(fig, [3 2]);
layout.RowHeight = {68, '1x', 180};
layout.ColumnWidth = {'1x', '1x'};

prompt = uilabel(layout, 'Text', ...
    ['Move one lever at a time. Sample count changes the averaging horizon; ' ...
    'noise RMS stretches one standardized realization; calibration bias ' ...
    'moves the center without changing random standard error.'], ...
    'WordWrap', 'on', 'FontWeight', 'bold');
prompt.Layout.Row = 1;
prompt.Layout.Column = [1 2];

sampleAxes = uiaxes(layout);
sampleAxes.Layout.Row = 2;
sampleAxes.Layout.Column = 1;
meanAxes = uiaxes(layout);
meanAxes.Layout.Row = 2;
meanAxes.Layout.Column = 2;

controls = uigridlayout(layout, [3 5]);
controls.Layout.Row = 3;
controls.Layout.Column = [1 2];
controls.RowHeight = {28, 58, 76};
controls.ColumnWidth = {220, 240, 220, 240, '1x'};

sampleCountLabel = uilabel(controls, ...
    'Text', 'Sample count N (samples)');
sampleCountLabel.Layout.Row = 1;
sampleCountLabel.Layout.Column = 1;
sampleCountSpinner = uispinner(controls, 'Limits', [25 1000], ...
    'Step', 25, 'Value', 400, 'RoundFractionalValues', 'on');
sampleCountSpinner.Layout.Row = 2;
sampleCountSpinner.Layout.Column = 1;

noiseLabel = uilabel(controls, ...
    'Text', 'Noise RMS sigma (mV)');
noiseLabel.Layout.Row = 1;
noiseLabel.Layout.Column = 2;
noiseSlider = uislider(controls, 'Limits', [0.0 8.0], ...
    'Value', 4.0, 'MajorTicks', [0 1 2 4 6 8]);
noiseSlider.Layout.Row = 2;
noiseSlider.Layout.Column = 2;

seedLabel = uilabel(controls, 'Text', 'Realization seed');
seedLabel.Layout.Row = 1;
seedLabel.Layout.Column = 3;
seedSpinner = uispinner(controls, 'Limits', [0 10000], ...
    'Step', 1, 'Value', 505, 'RoundFractionalValues', 'on');
seedSpinner.Layout.Row = 2;
seedSpinner.Layout.Column = 3;

biasLabel = uilabel(controls, ...
    'Text', 'Calibration bias b (mV)');
biasLabel.Layout.Row = 1;
biasLabel.Layout.Column = 4;
biasSlider = uislider(controls, 'Limits', [-5.0 5.0], ...
    'Value', 0.0, 'MajorTicks', [-5 -3 0 3 5]);
biasSlider.Layout.Row = 2;
biasSlider.Layout.Column = 4;

resetButton = uibutton(controls, 'push', 'Text', 'Reset baseline');
resetButton.Layout.Row = 2;
resetButton.Layout.Column = 5;

summary = uilabel(controls, 'Text', '', 'WordWrap', 'on');
summary.Layout.Row = 3;
summary.Layout.Column = [1 5];

sampleCountSpinner.ValueChangedFcn = @(~,~) updatePlots();
noiseSlider.ValueChangedFcn = @(~,~) updatePlots();
seedSpinner.ValueChangedFcn = @(~,~) updatePlots();
biasSlider.ValueChangedFcn = @(~,~) updatePlots();
resetButton.ButtonPushedFcn = @(~,~) resetBaseline();
updatePlots();

    function resetBaseline()
        sampleCountSpinner.Value = 400;
        noiseSlider.Value = 4.0;
        seedSpinner.Value = 505;
        biasSlider.Value = 0.0;
        updatePlots();
    end

    function updatePlots()
        trueSignalMillivolts = 12.0;
        out = modelFcn(sampleCountSpinner.Value, ...
            trueSignalMillivolts, noiseSlider.Value, ...
            seedSpinner.Value, biasSlider.Value);

        cla(sampleAxes);
        plot(sampleAxes, out.observation_counts, ...
            out.measurements_millivolts, '.', 'MarkerSize', 7);
        hold(sampleAxes, 'on');
        plot(sampleAxes, [1 out.sample_count], ...
            [out.true_signal_millivolts out.true_signal_millivolts], ...
            '--', 'LineWidth', 1.4);
        plot(sampleAxes, [1 out.sample_count], ...
            [out.expected_measurement_center_millivolts ...
            out.expected_measurement_center_millivolts], ':', ...
            'LineWidth', 1.4);
        hold(sampleAxes, 'off');
        grid(sampleAxes, 'on');
        xlabel(sampleAxes, 'Observation count n (samples)');
        ylabel(sampleAxes, 'Sensor reading X_i (mV)');
        title(sampleAxes, 'Raw readings do not become quieter');
        stableSampleLimitsMillivolts = [-45 70];
        sampleValuesMillivolts = [out.measurements_millivolts, ...
            out.true_signal_millivolts, ...
            out.expected_measurement_center_millivolts];
        samplePaddingMillivolts = max(1.0, ...
            0.05 * (max(sampleValuesMillivolts) - ...
            min(sampleValuesMillivolts)));
        sampleYLimitsMillivolts = [ ...
            min(stableSampleLimitsMillivolts(1), ...
            min(sampleValuesMillivolts) - samplePaddingMillivolts), ...
            max(stableSampleLimitsMillivolts(2), ...
            max(sampleValuesMillivolts) + samplePaddingMillivolts)];
        ylim(sampleAxes, sampleYLimitsMillivolts);

        cla(meanAxes);
        plot(meanAxes, out.observation_counts, ...
            out.running_sample_mean_millivolts, 'LineWidth', 1.5);
        hold(meanAxes, 'on');
        plot(meanAxes, [1 out.sample_count], ...
            [out.true_signal_millivolts out.true_signal_millivolts], ...
            '--', 'LineWidth', 1.4);
        plot(meanAxes, out.observation_counts, ...
            out.two_standard_error_lower_millivolts, ':');
        plot(meanAxes, out.observation_counts, ...
            out.two_standard_error_upper_millivolts, ':');
        hold(meanAxes, 'off');
        grid(meanAxes, 'on');
        xlabel(meanAxes, 'Observation count n (samples)');
        ylabel(meanAxes, 'Running sample mean (mV)');
        title(meanAxes, 'Averaging reduces random error, not bias');
        stableMeanLimitsMillivolts = [-10 35];
        meanValuesMillivolts = [out.running_sample_mean_millivolts, ...
            out.two_standard_error_lower_millivolts, ...
            out.two_standard_error_upper_millivolts, ...
            out.true_signal_millivolts, ...
            out.expected_measurement_center_millivolts];
        meanPaddingMillivolts = max(1.0, ...
            0.05 * (max(meanValuesMillivolts) - ...
            min(meanValuesMillivolts)));
        meanYLimitsMillivolts = [ ...
            min(stableMeanLimitsMillivolts(1), ...
            min(meanValuesMillivolts) - meanPaddingMillivolts), ...
            max(stableMeanLimitsMillivolts(2), ...
            max(meanValuesMillivolts) + meanPaddingMillivolts)];
        ylim(meanAxes, meanYLimitsMillivolts);

        summary.Text = sprintf(['N = %d samples | sigma = %.2f mV | seed = %d | ' ...
            'bias = %.2f mV | measurement center = %.2f mV\n' ...
            'final mean = %.4f mV | target error = %.4f mV | ' ...
            'theoretical SE = %.4f mV | target RMSE = %.4f mV'], ...
            out.sample_count, out.noise_standard_deviation_millivolts, ...
            out.seed, out.calibration_bias_millivolts, ...
            out.expected_measurement_center_millivolts, ...
            out.final_sample_mean_millivolts, ...
            out.final_error_from_true_millivolts, ...
            out.final_standard_error_millivolts, ...
            out.final_target_rmse_millivolts);
        drawnow limitrate;
    end
end
