function run_checks
%RUN_CHECKS Independent numerical, limiting, and failure checks for P05.

checkCallerRngState = rng;
restoreCheckCallerRng = onCleanup(@() rng(checkCallerRngState)); %#ok<NASGU>

baselineA = model(400, 12.0, 4.0, 505, 0.0);
baselineB = model(400, 12.0, 4.0, 505, 0.0);
assert(isequal(baselineA, baselineB), ...
    'Repeated calls with identical inputs must be deterministic.');
assert(abs(baselineA.final_standard_error_millivolts - 0.2) < 1e-12, ...
    'Baseline standard error must equal 4/sqrt(400) = 0.2 mV.');
independentRunningMean = ...
    cumsum(baselineA.measurements_millivolts) ./ (1:400);
assert(max(abs(baselineA.running_sample_mean_millivolts - ...
    independentRunningMean)) < 1e-12, ...
    'Running means must equal independent cumulative-sum arithmetic.');
assert(abs(baselineA.final_sample_mean_millivolts - ...
    sum(baselineA.measurements_millivolts) / 400) < 1e-12, ...
    'The final running mean must equal the ordinary sample mean.');
assert(max(abs(baselineA.theoretical_standard_error_millivolts - ...
    4.0 ./ sqrt(1:400))) < 1e-12, ...
    'Standard error must follow sigma/sqrt(n).');
assert(max(abs(baselineA.theoretical_target_rmse_millivolts - ...
    baselineA.theoretical_standard_error_millivolts)) < 1e-12, ...
    'With zero bias, target RMSE must equal random standard error.');

fixtureNoise = [-2 -1 0 1 2];
fixture = model(5, 12.0, 4.0, 505, 0.0, fixtureNoise);
independentMeasurements = [4 8 12 16 20];
independentMeans = [4 6 8 10 12];
assert(isequal(fixture.measurements_millivolts, ...
    independentMeasurements), ...
    'The supplied-noise fixture must obey X_i = mu + b + sigma*Z_i.');
assert(isequal(fixture.running_sample_mean_millivolts, ...
    independentMeans), ...
    'The supplied-noise fixture must produce exact cumulative means.');
assert(max(abs(fixture.theoretical_standard_error_millivolts - ...
    4 ./ sqrt(1:5))) < 1e-12, ...
    'The fixture standard-error curve must match independent arithmetic.');

wiggleNoise = [1 -1 1 -1];
wiggle = model(4, 12.0, 4.0, 505, 0.0, wiggleNoise);
independentWiggleMeans = [16 12 40/3 12];
assert(max(abs(wiggle.running_sample_mean_millivolts - ...
    independentWiggleMeans)) < 1e-12, ...
    'The nonmonotone fixture must match independent cumulative means.');
absoluteWiggleErrors = abs(wiggle.running_error_from_true_millivolts);
assert(absoluteWiggleErrors(3) > absoluteWiggleErrors(2) && ...
    wiggle.theoretical_standard_error_millivolts(3) < ...
    wiggle.theoretical_standard_error_millivolts(2), ...
    ['Realized error may increase after another sample even while ' ...
    'the theoretical standard-error scale decreases.']);

oneSample = model(1, 12.0, 4.0, 505, 0.0, 2);
assert(oneSample.final_sample_mean_millivolts == 20.0 && ...
    oneSample.final_standard_error_millivolts == 4.0, ...
    'At N = 1, the sample mean is X_1 and standard error is sigma.');
zeroNoise = model(25, 12.0, 0.0, 505, 0.0, zeros(1, 25));
assert(all(zeroNoise.measurements_millivolts == 12.0) && ...
    all(zeroNoise.running_sample_mean_millivolts == 12.0) && ...
    all(zeroNoise.theoretical_standard_error_millivolts == 0.0), ...
    'Zero noise and zero bias must recover the true signal exactly.');
biasedZeroNoise = model(25, 12.0, 0.0, 505, 3.0, zeros(1, 25));
assert(all(biasedZeroNoise.running_sample_mean_millivolts == 15.0) && ...
    all(biasedZeroNoise.running_error_from_true_millivolts == 3.0) && ...
    all(biasedZeroNoise.theoretical_target_rmse_millivolts == 3.0), ...
    'Zero random noise cannot remove a fixed 3 mV calibration bias.');

prefix25 = model(25, 12.0, 4.0, 505, 0.0);
prefix100 = model(100, 12.0, 4.0, 505, 0.0);
prefix400 = model(400, 12.0, 4.0, 505, 0.0);
assert(isequal(prefix25.measurements_millivolts, ...
    prefix400.measurements_millivolts(1:25)) && ...
    isequal(prefix100.measurements_millivolts, ...
    prefix400.measurements_millivolts(1:100)), ...
    'The sample-count sweep must preserve seeded record prefixes.');
assert(abs(prefix25.final_standard_error_millivolts - 0.8) < 1e-12 && ...
    abs(prefix100.final_standard_error_millivolts - 0.4) < 1e-12 && ...
    abs(prefix400.final_standard_error_millivolts - 0.2) < 1e-12, ...
    'The sample-count sweep must expose 0.8, 0.4, and 0.2 mV standard errors.');
assert(abs(prefix400.final_standard_error_millivolts ^ 2 - ...
    prefix100.final_standard_error_millivolts ^ 2 / 4) < 1e-12, ...
    'Quadrupling sample count must quarter mean variance.');

noiseOne = model(400, 12.0, 1.0, 505, 0.0);
noiseFour = model(400, 12.0, 4.0, 505, 0.0);
noiseEight = model(400, 12.0, 8.0, 505, 0.0);
assert(isequal(noiseOne.standardized_noise, ...
    noiseFour.standardized_noise) && ...
    isequal(noiseOne.standardized_noise, noiseEight.standardized_noise), ...
    'The noise-scale sweep must preserve its standardized realization.');
assert(max(abs(noiseFour.running_random_error_millivolts - ...
    4 * noiseOne.running_random_error_millivolts)) < 1e-10 && ...
    max(abs(noiseEight.running_random_error_millivolts - ...
    8 * noiseOne.running_random_error_millivolts)) < 1e-10, ...
    'Running random error must scale linearly with sigma.');
assert(noiseOne.final_standard_error_millivolts == 0.05 && ...
    noiseFour.final_standard_error_millivolts == 0.20 && ...
    noiseEight.final_standard_error_millivolts == 0.40, ...
    'The noise sweep must expose 0.05, 0.20, and 0.40 mV final standard errors.');

translated = model(5, 22.0, 4.0, 505, 0.0, fixtureNoise);
assert(isequal(translated.measurements_millivolts, ...
    fixture.measurements_millivolts + 10.0) && ...
    isequal(translated.running_sample_mean_millivolts, ...
    fixture.running_sample_mean_millivolts + 10.0) && ...
    isequal(translated.running_error_from_true_millivolts, ...
    fixture.running_error_from_true_millivolts), ...
    'Translation of the true signal must not change random error.');

biased = model(5, 12.0, 4.0, 505, 3.0, fixtureNoise);
assert(max(abs((biased.measurements_millivolts - ...
    fixture.measurements_millivolts) - 3.0)) < 1e-12 && ...
    max(abs((biased.running_sample_mean_millivolts - ...
    fixture.running_sample_mean_millivolts) - 3.0)) < 1e-12, ...
    'A common calibration offset must shift every reading and mean by 3 mV.');
independentBiasedRmse = sqrt(3.0 ^ 2 + (4.0 ./ sqrt(1:5)) .^ 2);
assert(max(abs(biased.theoretical_target_rmse_millivolts - ...
    independentBiasedRmse)) < 1e-12, ...
    'Biased target RMSE must equal sqrt(bias^2 + sigma^2/n).');
repairedMeasurements = biased.measurements_millivolts - 3.0;
repairedMeans = cumsum(repairedMeasurements) ./ (1:5);
assert(max(abs(repairedMeans - ...
    fixture.running_sample_mean_millivolts)) < 1e-12, ...
    'Subtracting a known calibration offset must repair the biased record.');

rng(905, 'twister');
expectedNextUniformValue = rand;
expectedNextNormalValue = randn;
rng(905, 'twister');
model(400, 12.0, 4.0, 505, 0.0);
observedNextUniformValue = rand;
observedNextNormalValue = randn;
assert(observedNextUniformValue == expectedNextUniformValue && ...
    observedNextNormalValue == expectedNextNormalValue, ...
    'model must leave the caller RNG state unchanged.');

assertAnyError(@() model([25 100], 12.0, 4.0, 505, 0.0));
assertAnyError(@() model(25, 12.0 + 1i, 4.0, 505, 0.0));
assertAnyError(@() model(25, NaN, 4.0, 505, 0.0));
assertAnyError(@() model(25, 12.0, Inf, 505, 0.0));
assertAnyError(@() model(25, 12.0, 4.0, NaN, 0.0));
assertAnyError(@() model(25, 12.0, 4.0, 505, Inf));
assertError(@() model(0, 12.0, 4.0, 505, 0.0), ...
    'P05:InvalidSampleCount');
assertError(@() model(2.5, 12.0, 4.0, 505, 0.0), ...
    'P05:InvalidSampleCount');
assertError(@() model(25, 12.0, -0.1, 505, 0.0), ...
    'P05:InvalidNoiseScale');
assertError(@() model(25, 12.0, 4.0, -1, 0.0), ...
    'P05:InvalidSeed');
assertError(@() model(25, 12.0, 4.0, 1.5, 0.0), ...
    'P05:InvalidSeed');
assertError(@() model(25, 12.0, 4.0, 4294967296, 0.0), ...
    'P05:InvalidSeed');
assertError(@() model(5, 12.0, 4.0, 505, 0.0, [0 1]), ...
    'P05:SampleCountMismatch');
assertError(@() model(5, 12.0, 4.0, 505, 0.0, ...
    [0 1 2 NaN 4]), 'P05:InvalidNoiseFixture');
assertError(@() model(50001, 12.0, 4.0, 505, 0.0), ...
    'P05:ResourceBound');
assertError(@() model(25, 1000001, 4.0, 505, 0.0), ...
    'P05:ResourceBound');
assertError(@() model(25, 12.0, 1000001, 505, 0.0), ...
    'P05:ResourceBound');
assertError(@() model(25, 12.0, 4.0, 505, -1000001), ...
    'P05:ResourceBound');
assertError(@() model(1, 1000000, 1000000, 505, ...
    1000000, realmax), 'P05:NumericalFailure');
maximumAccepted = model(50000, 12.0, 0.0, 4294967295, ...
    0.0, zeros(1, 50000));
assert(maximumAccepted.sample_count == 50000 && ...
    maximumAccepted.seed == 4294967295, ...
    'The documented sample-count and seed resource boundaries must be accepted.');

disp('P05 checks passed.');
end

function assertAnyError(operation)
didThrow = false;
try
    operation();
catch
    didThrow = true;
end
assert(didThrow, 'Expected malformed input to be rejected.');
end

function assertError(operation, expectedIdentifier)
caughtIdentifier = '';
try
    operation();
catch caught
    caughtIdentifier = caught.identifier;
end
assert(strcmp(caughtIdentifier, expectedIdentifier), ...
    'Expected error %s but caught %s.', expectedIdentifier, caughtIdentifier);
end
