function run_checks
%RUN_CHECKS Independent numerical, limiting, and failure checks for P03.

checkCallerRngState = rng;
restoreCheckCallerRng = onCleanup(@() rng(checkCallerRngState)); %#ok<NASGU>

baselineA = model(400, 0.70, 1.0, 1.5, 303);
baselineB = model(400, 0.70, 1.0, 1.5, 303);
assert(isequal(baselineA.samples_a_millimeters, ...
    baselineB.samples_a_millimeters), ...
    'Seeded Sensor A samples must be deterministic.');
assert(isequal(baselineA.samples_b_millimeters, ...
    baselineB.samples_b_millimeters), ...
    'Seeded Sensor B samples must be deterministic.');

independentMeanA = sum(baselineA.samples_a_millimeters) / ...
    baselineA.sample_count;
independentMeanB = sum(baselineA.samples_b_millimeters) / ...
    baselineA.sample_count;
independentCenteredA = baselineA.samples_a_millimeters - independentMeanA;
independentCenteredB = baselineA.samples_b_millimeters - independentMeanB;
independentVarianceA = sum(independentCenteredA .^ 2) / ...
    baselineA.sample_count;
independentVarianceB = sum(independentCenteredB .^ 2) / ...
    baselineA.sample_count;
independentCovariance = sum(independentCenteredA .* independentCenteredB) / ...
    baselineA.sample_count;
independentCorrelation = independentCovariance / ...
    sqrt(independentVarianceA * independentVarianceB);
assert(abs(baselineA.mean_a_millimeters - independentMeanA) < 1e-12 && ...
    abs(baselineA.mean_b_millimeters - independentMeanB) < 1e-12, ...
    'Reported means must match an independent sum-over-N calculation.');
assert(abs(baselineA.covariance_millimeters_squared - ...
    independentCovariance) < 1e-12, ...
    'Reported covariance must match an independent centered-product calculation.');
assert(abs(baselineA.correlation_coefficient - ...
    independentCorrelation) < 1e-12, ...
    'Reported correlation must match independent covariance normalization.');
assert(abs(baselineA.covariance_millimeters_squared - 1.05) < 1e-12, ...
    'The baseline covariance limit must equal rho*sigma_A*sigma_B.');
assert(abs(baselineA.correlation_coefficient - 0.70) < 1e-12, ...
    'The controlled baseline correlation must equal rho.');
assert(abs(baselineA.standard_deviation_a_millimeters - 1.0) < 1e-12 && ...
    abs(baselineA.standard_deviation_b_millimeters - 1.5) < 1e-12, ...
    'The orthogonalized drivers must retain the requested N-normalized RMS scales.');

reverseCovariance = sum(independentCenteredB .* independentCenteredA) / ...
    baselineA.sample_count;
assert(abs(reverseCovariance - independentCovariance) < 1e-12, ...
    'Covariance must be symmetric when the sensor order is reversed.');
assert(abs(independentCovariance) <= ...
    sqrt(independentVarianceA * independentVarianceB) + 1e-12, ...
    'Covariance must obey the Cauchy-Schwarz bound.');
baselinePsdTolerance = 1e-12 * max(1, ...
    baselineA.variance_a_millimeters_squared * ...
    baselineA.variance_b_millimeters_squared);
assert(baselineA.covariance_determinant_millimeters_fourth >= ...
    -baselinePsdTolerance, ...
    'The 2-by-2 covariance matrix must be positive semidefinite.');
assert(abs(baselineA.covariance_determinant_millimeters_fourth - ...
    baselineA.analytic_psd_margin_millimeters_fourth) <= ...
    baselinePsdTolerance, ...
    'The empirical determinant must match the analytic PSD margin.');
assert(max(max(abs(baselineA.covariance_matrix_millimeters_squared - ...
    baselineA.covariance_matrix_millimeters_squared.'))) < 1e-12, ...
    'The covariance matrix must be symmetric.');
assert(abs(baselineA.n_minus_one_covariance_millimeters_squared - ...
    baselineA.sample_count / (baselineA.sample_count - 1) * ...
    baselineA.covariance_millimeters_squared) < 1e-12, ...
    'N-1 covariance must equal N/(N-1) times the N-normalized record moment.');

zeroMotion = model(400, 0.0, 1.0, 1.5, 303);
positiveLimit = model(400, 1.0, 1.0, 1.5, 303);
negativeLimit = model(400, -1.0, 1.0, 1.5, 303);
assert(abs(zeroMotion.covariance_millimeters_squared) < 1e-12 && ...
    abs(zeroMotion.correlation_coefficient) < 1e-12, ...
    'Orthogonal motion must have zero covariance and correlation.');
assert(abs(positiveLimit.covariance_millimeters_squared - 1.5) < 1e-12 && ...
    abs(positiveLimit.correlation_coefficient - 1.0) < 1e-12, ...
    'rho = 1 must produce the perfect same-direction limit.');
assert(abs(negativeLimit.covariance_millimeters_squared + 1.5) < 1e-12 && ...
    abs(negativeLimit.correlation_coefficient + 1.0) < 1e-12, ...
    'rho = -1 must produce the perfect opposite-direction limit.');
positiveLimitTolerance = 1e-12 * max(1, ...
    positiveLimit.variance_a_millimeters_squared * ...
    positiveLimit.variance_b_millimeters_squared);
negativeLimitTolerance = 1e-12 * max(1, ...
    negativeLimit.variance_a_millimeters_squared * ...
    negativeLimit.variance_b_millimeters_squared);
assert(abs(positiveLimit.covariance_determinant_millimeters_fourth) <= ...
    positiveLimitTolerance && ...
    abs(negativeLimit.covariance_determinant_millimeters_fourth) <= ...
    negativeLimitTolerance && ...
    positiveLimit.analytic_psd_margin_millimeters_fourth == 0 && ...
    negativeLimit.analytic_psd_margin_millimeters_fourth == 0, ...
    'Perfect linear co-motion must make the covariance matrix singular.');

negativeSweep = model(400, -0.80, 1.0, 1.5, 303);
zeroSweep = model(400, 0.00, 1.0, 1.5, 303);
positiveSweep = model(400, 0.80, 1.0, 1.5, 303);
assert(negativeSweep.covariance_millimeters_squared < 0 && ...
    abs(zeroSweep.covariance_millimeters_squared) < 1e-12 && ...
    positiveSweep.covariance_millimeters_squared > 0, ...
    'The rho sweep must isolate negative, zero, and positive covariance.');
assert(isequal(negativeSweep.centered_a_millimeters, ...
    zeroSweep.centered_a_millimeters) && ...
    isequal(zeroSweep.centered_a_millimeters, ...
    positiveSweep.centered_a_millimeters), ...
    'The rho sweep must preserve Sensor A and the seeded base realization.');

smallScale = model(400, 0.70, 1.0, 0.50, 303);
largeScale = model(400, 0.70, 1.0, 2.00, 303);
assert(max(abs(largeScale.centered_b_millimeters - ...
    4 * smallScale.centered_b_millimeters)) < 1e-12, ...
    'The Sensor B scale sweep must multiply only Sensor B deviations.');
assert(abs(largeScale.covariance_millimeters_squared - ...
    4 * smallScale.covariance_millimeters_squared) < 1e-12, ...
    'Covariance must scale linearly with Sensor B RMS scale.');
assert(abs(largeScale.correlation_coefficient - ...
    smallScale.correlation_coefficient) < 1e-12, ...
    'Correlation must be invariant to a positive Sensor B scale change.');
assert(isequal(smallScale.centered_a_millimeters, ...
    largeScale.centered_a_millimeters), ...
    'The Sensor B scale sweep must preserve Sensor A.');

unshifted = model(400, 0.70, 1.0, 1.5, 303, 0.0, 0.0);
shifted = model(400, 0.70, 1.0, 1.5, 303, 40.0, 30.0);
assert(max(abs(unshifted.centered_a_millimeters - ...
    shifted.centered_a_millimeters)) < 1e-12 && ...
    max(abs(unshifted.centered_b_millimeters - ...
    shifted.centered_b_millimeters)) < 1e-12, ...
    'Adding constant offsets must preserve both centered records.');
assert(abs(unshifted.covariance_millimeters_squared - ...
    shifted.covariance_millimeters_squared) < 1e-12, ...
    'Centered covariance must be translation invariant.');

broken = model(400, 0.0, 1.0, 1.0, 303, 40.0, 30.0);
assert(abs(broken.covariance_millimeters_squared) < 1e-12, ...
    'The broken fixture must retain zero centered covariance.');
assert(abs(broken.raw_cross_moment_millimeters_squared - 1200.0) < 1e-10, ...
    'The uncentered raw cross-moment must expose the 40 mm by 30 mm offset product.');
assert(abs(broken.raw_cross_moment_millimeters_squared - ...
    (broken.covariance_millimeters_squared + ...
    broken.mean_a_millimeters * broken.mean_b_millimeters)) < 1e-10, ...
    'The raw cross-moment must equal covariance plus the product of means.');
assert(abs(broken.raw_cross_moment_millimeters_squared - ...
    broken.covariance_millimeters_squared) > 1000, ...
    'Skipping centering must produce a recognizable false shared-motion symptom.');

nonlinearA = -3:3;
nonlinearB = nonlinearA .^ 2;
nonlinearCenteredA = nonlinearA - sum(nonlinearA) / numel(nonlinearA);
nonlinearCenteredB = nonlinearB - sum(nonlinearB) / numel(nonlinearB);
nonlinearCovariance = sum(nonlinearCenteredA .* nonlinearCenteredB) / ...
    numel(nonlinearA);
assert(abs(nonlinearCovariance) < 1e-12 && ...
    nonlinearB(1) == nonlinearB(end) && nonlinearB(4) == 0, ...
    'Zero covariance must not be interpreted as absence of nonlinear dependence.');

rng(903, 'twister');
expectedNextUniformValue = rand;
expectedNextNormalValue = randn;
rng(903, 'twister');
model(400, 0.70, 1.0, 1.5, 303);
observedNextUniformValue = rand;
observedNextNormalValue = randn;
assert(observedNextUniformValue == expectedNextUniformValue && ...
    observedNextNormalValue == expectedNextNormalValue, ...
    'model must restore the caller RNG state for uniform and normal draws.');

assertAnyError(@() model(2, 0.0, 1.0, 1.0, 303));
assertAnyError(@() model(10.5, 0.0, 1.0, 1.0, 303));
assertAnyError(@() model(10, NaN, 1.0, 1.0, 303));
assertAnyError(@() model(10, 1i, 1.0, 1.0, 303));
assertAnyError(@() model(10, 0.0, Inf, 1.0, 303));
assertAnyError(@() model(10, 0.0, 1.0, 1.0, -1));
assertAnyError(@() model(10, 0.0, 1.0, 1.0, 303, NaN, 0));
assertError(@() model(10, 1.01, 1.0, 1.0, 303), ...
    'P03:InvalidCorrelation');
assertError(@() model(10, -1.01, 1.0, 1.0, 303), ...
    'P03:InvalidCorrelation');
assertError(@() model(50001, 0.0, 1.0, 1.0, 303), ...
    'P03:ResourceBound');
assertError(@() model(10, 0.0, 0.0, 1.0, 303), ...
    'P03:ResourceBound');
assertError(@() model(10, 0.0, 1e-7, 1.0, 303), ...
    'P03:ResourceBound');
assertError(@() model(10, 0.0, 1.0, 1000001, 303), ...
    'P03:ResourceBound');
assertError(@() model(10, 0.0, 1.0, 1.0, 4294967296), ...
    'P03:InvalidSeed');
assertError(@() model(10, 0.0, 1.0, 1.0, 303, 1000001, 0), ...
    'P03:ResourceBound');
assertError(@() model(10, 0.0, 1e-6, 1.0, 303, 1001, 0), ...
    'P03:ResourceBound');
minimumAccepted = model(3, 0.0, 1.0, 1.0, 303);
assert(minimumAccepted.sample_count == 3 && ...
    abs(minimumAccepted.covariance_millimeters_squared) < 1e-12, ...
    'The three-pair orthogonal-driver boundary must remain accepted.');
maximumAccepted = model(50000, 0.0, 1.0, 1.0, 303);
assert(maximumAccepted.sample_count == 50000 && ...
    abs(maximumAccepted.covariance_millimeters_squared) < 1e-12, ...
    'The documented sample resource boundary must remain accepted.');

disp('P03 checks passed.');
end

function assertAnyError(operation)
didThrow = false;
try
    operation();
catch
    didThrow = true;
end
assert(didThrow, 'Expected malformed input to be rejected.');
end

function assertError(operation, expectedIdentifier)
caughtIdentifier = '';
try
    operation();
catch caught
    caughtIdentifier = caught.identifier;
end
assert(strcmp(caughtIdentifier, expectedIdentifier), ...
    'Expected error %s but caught %s.', expectedIdentifier, caughtIdentifier);
end
